server:
  port: 8900

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
        order_updates: true
        jdbc:
          batch_size: 20

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: mysecretpassword

kafka:
  bootstrap-server: localhost:9092
  client-id: portfoliosvc
  acks: all
  retries: 3
  key-serializer: org.apache.kafka.common.serialization.StringSerializer
  value-serializer: org.apache.kafka.common.serialization.StringSerializer
  outbound-topic: portfolio-outbound
